package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_delivery", "id", Delivery.class);
		arp.addMapping("t_fchannel", "fchannel_id", Fchannel.class);
		arp.addMapping("t_goods", "goods_id", Goods.class);
		arp.addMapping("t_orders", "id", Orders.class);
		arp.addMapping("t_package", "package_id", Package.class);
		arp.addMapping("t_zchannel", "zchannel_id", Zchannel.class);
		arp.addMapping("t_zxad", "id", Zxad.class);
		arp.addMapping("t_zxadmin", "adminId", Zxadmin.class);
		arp.addMapping("t_zxarticle", "article_id", Zxarticle.class);
		arp.addMapping("t_zxarticle_category", "article_category_id", ZxarticleCategory.class);
		arp.addMapping("t_zxbanner", "banner_id", Zxbanner.class);
		arp.addMapping("t_zxbrand", "brandId", Zxbrand.class);
		arp.addMapping("t_zxdegrees", "degreesId", Zxdegrees.class);
		arp.addMapping("t_zxnavigation", "navigation_id", Zxnavigation.class);
		arp.addMapping("t_zxprice", "priceId", Zxprice.class);
		arp.addMapping("t_zxrole", "roleId", Zxrole.class);
		arp.addMapping("t_zxscreen", "screenId", Zxscreen.class);
	}
}

