package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseDelivery;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Delivery extends BaseDelivery<Delivery> {
	public static final Delivery dao = new Delivery();
	
	public Page<Delivery> pageTjset(int page,int size,String atime,String btime,String zchName){
		String sqla="SELECT d.id,z.zchannel_name,"
				+ "IFNULL((SELECT SUM(s.settlementMoney) FROM t_settlement s "
				+ "WHERE s.zchannel=d.zchannel_id ),0) AS paidMOney,"
				+ "IFNULL((SELECT CONCAT(s.startTime,'至',s.endTime) FROM t_settlement s "
				+ "WHERE s.zchannel=d.zchannel_id ORDER BY s.endTime DESC  LIMIT 1),'') AS setTime,"
				+ "(IFNULL((SELECT (SUM(o.orderMoney)-SUM(o.logistMoney))*(d.goods_channel_rate/100) FROM t_orders o "
				+ "WHERE o.goodsId =d.goods_id AND o.zchannel_id=d.zchannel_id),0)-"
				+ "IFNULL((SELECT SUM(s.settlementMoney) FROM t_settlement s "
				+ "WHERE s.zchannel=d.zchannel_id ),0)) AS noMoney";
		String sqlb="FROM t_delivery d LEFT JOIN t_zchannel z ON d.zchannel_id = z.zchannel_id where 1=1 ";
//				
//		if(atime !=null && !atime.equals("")){
//			sqlb += " and o.addTime > '"+atime+"'";
//		}
//		if(!btime.equals("")){
//			sqlb += " and o.addTime < '"+btime+"'";
//		}
		if(!zchName.equals("")){
			sqlb += " and z.zchannel_name like '%"+zchName+"%' ";
		}
//		sqlb += "ORDER BY o.addTime desc";
		return paginate(page, size, sqla, sqlb);
	}
	
	public Page<Delivery> channel(int page,int size,String atime,String btime,String goodsName,String zchName){
		String sqla="SELECT z.zchannel_name,d.start_time,d.end_time,g.goods_name,d.goods_channel_rate,"
					+"(SELECT SUM(o.logistMoney) FROM t_orders o WHERE o.zchannel_id=d.zchannel_id ) AS logistMoney ,"
					+"(SELECT COUNT(1) FROM t_orders o WHERE o.zchannel_id=d.zchannel_id) AS ordersNumber,"
					+"(SELECT COUNT(1) FROM t_orders o WHERE o.zchannel_id=d.zchannel_id AND o.status=3) AS ordersNumbers,"
					+"(SELECT SUM(o.orderMoney) FROM t_orders o WHERE o.zchannel_id=d.zchannel_id ) AS orderMoney,"
					+"IFNULL((SELECT SUM(o.orderMoney) FROM t_orders o WHERE o.zchannel_id=d.zchannel_id AND o.status=3),0) AS orderMoneys,"
					+"IFNULL((SELECT SUM(o.orderMoney) FROM t_orders o WHERE o.zchannel_id=d.zchannel_id AND o.status=3)*(d.goods_channel_rate/100),0) AS orderMoneyx";
		String sqlb="FROM t_delivery d LEFT JOIN t_goods g ON d.goods_id = g.goods_id"
					+" LEFT JOIN t_zchannel z ON d.zchannel_id=z.zchannel_id where 1=1 ";
		if(atime !=null && !atime.equals("")){
			sqlb += " and d.start_time > '"+atime+"'";
		}
		if(!btime.equals("")){
			sqlb += " and d.end_time < '"+btime+"'";
		}
		if(!goodsName.equals("")){
			sqlb += " and g.goods_name like '%"+goodsName+"%' ";
		}
		if(!zchName.equals("")){
			sqlb += " and z.zchannel_name like '%"+zchName+"%' ";
		}
	//	sqlb += "ORDER BY o.addTime desc";
		return paginate(page, size, sqla, sqlb);
	}
	public List<Record> list(String atime,String btime,String goodsName,String zchName){
		String sql="SELECT z.zchannel_name,d.start_time,d.end_time,g.goods_name,d.goods_channel_rate, "
				+"(SELECT SUM(o.logistMoney) FROM t_orders o WHERE o.zchannel_id=d.zchannel_id ) AS logistMoney , "
				+"(SELECT COUNT(1) FROM t_orders o WHERE o.zchannel_id=d.zchannel_id) AS ordersNumber, "
				+"(SELECT COUNT(1) FROM t_orders o WHERE o.zchannel_id=d.zchannel_id AND o.status=3) AS ordersNumbers, "
				+"(SELECT SUM(o.orderMoney) FROM t_orders o WHERE o.zchannel_id=d.zchannel_id ) AS orderMoney, "
				+"IFNULL((SELECT SUM(o.orderMoney) FROM t_orders o WHERE o.zchannel_id=d.zchannel_id AND o.status=3),0) AS orderMoneys, "
				+" IFNULL(((SELECT SUM(o.orderMoney) FROM t_orders o WHERE o.zchannel_id=d.zchannel_id AND o.status=3)-(SELECT SUM(o.logistMoney) FROM t_orders o WHERE o.zchannel_id=d.zchannel_id ))*(d.goods_channel_rate/100),0) AS orderMoneyx"
				+" FROM t_delivery d LEFT JOIN t_goods g ON d.goods_id = g.goods_id "
				+" LEFT JOIN t_zchannel z ON d.zchannel_id=z.zchannel_id where 1=1 ";
	if(atime !=null && !atime.equals("")){
		sql += " and d.start_time > '"+atime+"'";
	}
	if(!btime.equals("")){
		sql += " and d.end_time < '"+btime+"'";
	}
	if(!goodsName.equals("")){
		sql += " and g.goods_name like '%"+goodsName+"%' ";
	}
	if(!zchName.equals("")){
		sql += " and z.zchannel_name like '%"+zchName+"%' ";
	}
		return Db.find(sql);
	}
}
