package com.demo.common.model;

import com.demo.common.model.base.BaseFchannel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Fchannel extends BaseFchannel<Fchannel> {
	public static final Fchannel dao = new Fchannel();
	public void d(){
		String sql="SELECT f.fchannel_id,f.fchannel_name,COUNT(o.id) AS orderNumber, IFNULL(SUM(o.orderMoney),'') AS orderMoney"
					+" FROM t_fchannel f LEFT JOIN t_orders o "
					+" ON f.fchannel_id=o.fchannel_id  "
					+" GROUP BY f.fchannel_id";
	}
}
