package com.demo.common.model;

import com.demo.common.model.base.BaseGoods;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goods extends BaseGoods<Goods> {
	public static final Goods dao = new Goods();
	public Page<Goods> pageGoods(int pageNumber, int pageSize){
		String sql ="from t_goods";
		return paginate(pageNumber, pageSize, "SELECT goods_id,goods_name,add_time", sql);
	}
}
