package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BasePackage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Package extends BasePackage<Package> {
	public static final Package dao = new Package();
	
	public List<Package> getPack(){
		return find("select * from t_package t");
	}
}
