package com.demo.common.model;

import com.demo.common.model.base.BaseTjorder;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tjorder extends BaseTjorder<Tjorder> {
	
	public static final Tjorder dao = new Tjorder();
	
	public Page<Tjorder> pageTjorder(int page,int size,String atime,String btime,String goodsName,String zchName){
		String sqla="SELECT o.id,g.goods_name,g.price,p.package_number,z.zchannel_name,o.addTime";
		String sqlb="FROM t_orders o "
				+ "LEFT JOIN t_goods g ON o.goodsId = g.goods_id "
				+ "LEFT JOIN t_package p ON o.package_id = p.package_id "
				+ "LEFT JOIN t_zchannel z ON o.zchannel_id = z.zchannel_id where 1=1 ";
		if(atime !=null && !atime.equals("")){
			sqlb += " and o.addTime < atime";
		}
		if(!btime.equals("")){
			sqlb += " and o.addTime > btime";
		}
		if(!goodsName.equals("")){
			sqlb += " and g.goods_name like '%"+goodsName+"%' ";
		}
		if(!zchName.equals("")){
			sqlb += " and z.zchannel_name like '%"+zchName+"%' ";
		}
		sqlb += "ORDER BY o.addTime desc";
		return paginate(page, size, sqla, sqlb);
	}
}
