package com.demo.common.model;

import com.demo.common.model.base.BaseZchannel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Zchannel extends BaseZchannel<Zchannel> {
	public static final Zchannel dao = new Zchannel();
}
