package com.demo.common.model;

import com.demo.common.model.base.BaseZxadmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Zxadmin extends BaseZxadmin<Zxadmin> {
	public static final Zxadmin dao = new Zxadmin();
	
	public Zxadmin findLogin(String name,String pwd){
		String sql = "SELECT * FROM t_zxadmin t WHERE t.admin ='"+name+"' AND t.password='"+pwd+"'";
		return findFirst(sql);
	}
}
