package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseZxad;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Zxad extends BaseZxad<Zxad> {
	public static final Zxad dao = new Zxad();
	
	public Page<Zxad> adData(int pageNumber, int pageSize,String title,int bannerId,int isShow,int s){
		String sql=" FROM t_zxad t LEFT JOIN t_zxbanner b ON t.banner_id = b.banner_id WHERE 1=1";
		if(title != null && !"".equals(title)){
			sql += " and t.title LIKE '%"+title+"%'";
		}
		if(bannerId >0){
			sql += " AND t.banner_id ="+bannerId;
		}
		if(isShow !=2){
			sql += "  AND t.isShow ="+isShow;
		}
		if(s!=0)
		sql += "  AND t.status != 0";
		if(s == 0)
			sql += "  AND t.status = 0";
		return paginate(pageNumber, pageSize, "SELECT t.*,b.banner_name", sql);
	}
	public List<Zxad> getAd(Integer id){
		String sql = "SELECT t.*,IFNULL(t.sort,99) s FROM t_zxad t WHERE banner_id ="+id+" ORDER BY s,t.add_time";
		return find(sql);
	}
	public int delete(String sId){
		String sql = "DELETE FROM t_zxad  WHERE id IN("+sId+")";
		try {
			return Db.update(sql);
		} catch (Exception e) {
			return 0;
		}
	}
}
