package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseZxarticle;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 * 文章
 */
@SuppressWarnings("serial")
public class Zxarticle extends BaseZxarticle<Zxarticle> {
	public static final Zxarticle dao = new Zxarticle();
	public List<Zxarticle> getToutiao(){
		//首页头条== id11 ，2级标题 
		return find("SELECT * FROM t_zxarticle zxa WHERE  zxa.article_category_id = 11 AND zxa.fpid =1  ORDER BY article_id desc LIMIT 2");
	}
	public List<Zxarticle> getTiaoArticle(){
		//首页头条== id11 ，3级标题 
	//	return find("SELECT * FROM t_zxarticle t WHERE t.article_category_id = 11 AND fpid <> 1 AND  (SELECT COUNT(b.article_id) FROM t_zxarticle b WHERE b.fpid=t.fpid AND b.article_id>=t.article_id)<=3;");
		return find("SELECT * FROM t_zxarticle t WHERE t.article_category_id = 11 AND fpid <> 1 LIMIT 8");
	}
	public List<Zxarticle> getZixun(){
		//酒业资讯== id20 
		return find("SELECT * FROM t_zxarticle zxa WHERE  zxa.article_category_id = 20  ORDER BY article_id desc LIMIT 8");
	}
	public List<Zxarticle> getWenhua(){
		//酒文化== id26
		return find("SELECT * FROM t_zxarticle zxa WHERE  zxa.article_category_id = 26  ORDER BY article_id desc LIMIT 8");
	}
	public List<Zxarticle> getDongtai(){
		//首页动态== id27 ，2级标题 
		return find("SELECT * FROM t_zxarticle zxa WHERE  zxa.article_category_id = 27 AND zxa.fpid =1  ORDER BY article_id desc LIMIT 3");
	}
	public List<Zxarticle> getDongArticle(){
		//首页动态== id27 ，3级标题 
		return find("SELECT * FROM t_zxarticle t WHERE t.article_category_id = 27 AND fpid <> 1 AND  (SELECT COUNT(b.article_id) FROM t_zxarticle b WHERE b.fpid=t.fpid AND b.article_id>=t.article_id)<=2;");
	}
	public List<Zxarticle> getCan(){
		//首页动态== id30 ，2级标题 
		return find("SELECT * FROM t_zxarticle zxa WHERE  zxa.article_category_id = 30 AND zxa.fpid =1  ORDER BY article_id desc LIMIT 3");
	}
	public List<Zxarticle> getCans(){
		//首页动态== id30 ，3级标题 
		return find("SELECT * FROM t_zxarticle t WHERE t.article_category_id = 30 AND fpid <> 1 AND  (SELECT COUNT(b.article_id) FROM t_zxarticle b WHERE b.fpid=t.fpid AND b.article_id>=t.article_id)<=2;");
	}
	public List<Zxarticle> getHuodong(){
		//活动== id28
		return find("SELECT * FROM t_zxarticle zxa WHERE  zxa.article_category_id = 28  ORDER BY article_id desc LIMIT 3");
	}
	public List<Zxarticle> getPinjian(){
		//活动== id29
		return find("SELECT * FROM t_zxarticle zxa WHERE  zxa.article_category_id = 29  ORDER BY article_id desc LIMIT 3");
	}
	public Page<Zxarticle> getCanyin(int pageNumber, int pageSize,int id,int fpid){
		String sql="from t_zxarticle t WHERE t.article_category_id = "+id+" AND fpid <> 1  ORDER BY article_id desc";
		if(fpid != 0 && fpid != 1){
			sql = "from t_zxarticle t WHERE t.article_category_id = "+id+" AND fpid = "+fpid+"  ORDER BY article_id desc";
		}
		return paginate(pageNumber, pageSize, "select *", sql);
	}
	public List<Zxarticle> getErtitle(){
		return find("SELECT * FROM t_zxarticle zxa WHERE  zxa.article_category_id = 30  AND fpid = 1  ORDER BY article_id desc");
	}
	public List<Zxarticle> getPaihang(){
		//排行榜== id 32
		return find("SELECT * FROM t_zxarticle zxa WHERE  zxa.article_category_id = 32  ORDER BY article_id desc LIMIT 3");
	}
	public List<Zxarticle> getXinwen(){
		//排热门新闻== id 33
		return find("SELECT * FROM t_zxarticle zxa WHERE  zxa.article_category_id = 33  ORDER BY article_id desc LIMIT 3");
	}
	public Zxarticle getById(int id){
		return findFirst("SELECT * FROM t_zxarticle a WHERE a.article_id = ?",id);
	}
	
	//admin
	public Page<Zxarticle> wzneirongData(int pageNumber, int pageSize,int status,int yiji,int isShow,String addTime,String wenztitle){
		String sql="FROM t_zxarticle t  LEFT JOIN t_zxarticle_category z ON t.article_category_id = z.article_category_id where 1=1 ";
		if(yiji != 0){
			sql +=" and t.article_category_id = "+yiji;
		}
		if(isShow != 2){
			sql +=" AND t.is_show = "+isShow;
		}
		if(!addTime.equals("")){
			sql +=" AND t.add_time like '%"+addTime+"%'";
		}
		if(!wenztitle.equals("")){
			sql +=" AND t.title like '%"+wenztitle+"%'";
		}
		if(status == 0){
			sql +=" and t.status =0 ORDER BY IFNULL(sort,99999), add_time DESC";
		}else{
			sql +=" and t.status >0 ORDER BY IFNULL(sort,99999), add_time DESC";
		}
		
		return paginate(pageNumber, pageSize, "SELECT t.*,z.article_category_name", sql);
	}
	
	public int delete(String sId){
		String sql = "DELETE FROM t_zxarticle  WHERE article_id IN("+sId+")";
		try {
			return Db.update(sql);
		} catch (Exception e) {
			return 0;
		}
	}
	
	public List<Zxarticle> geterjifl(int id){
		return find("SELECT * FROM t_zxarticle zxa WHERE  zxa.fpid =1 AND article_category_id = ?",id);
	}
	
}
