package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseZxbanner;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Zxbanner extends BaseZxbanner<Zxbanner> {
	public static final Zxbanner dao = new Zxbanner();
	//分类
	public Page<Zxbanner> bannerflData(int pageNumber, int pageSize){
		return paginate(pageNumber, pageSize, "select *", "from t_zxbanner t ");
	}
	public List<Zxbanner>  getflData(){
		return find("SELECT * FROM t_zxbanner");
	}
	public int delete(String sId){
		String sql = "DELETE FROM t_zxbanner  WHERE id IN("+sId+")";
		try {
			return Db.update(sql);
		} catch (Exception e) {
			return 0;
		}
	}
}
