package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseZxbrand;

/**
 * Generated by JFinal.
 * 品牌
 */
@SuppressWarnings("serial")
public class Zxbrand extends BaseZxbrand<Zxbrand> {
	public static final Zxbrand dao = new Zxbrand();
	
	public List<Zxbrand> getBrand(){
		//品牌
		return find("SELECT * FROM t_zxbrand t LIMIT 4");
	}
}
