package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseZxdegrees;

/**
 * Generated by JFinal.
 * 度数 、香型
 */
@SuppressWarnings("serial")
public class Zxdegrees extends BaseZxdegrees<Zxdegrees> {
	public static final Zxdegrees dao = new Zxdegrees();
	public List<Zxdegrees> getDegrees(Integer stutas){
		return find("SELECT * FROM t_zxdegrees t WHERE t.status =?",stutas);
	}
}
