package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseZxnavigation;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 * 导航栏
 */
@SuppressWarnings("serial")
public class Zxnavigation extends BaseZxnavigation<Zxnavigation> {
	public static final Zxnavigation dao = new Zxnavigation();
	
	public List<Zxnavigation> getNavigation(){
		return find("select * from t_zxnavigation");
	}
	
	public Page<Zxnavigation> adData(int pageNumber, int pageSize,int id){
		String sql ="from t_zxnavigation t  WHERE t.type = "+id+" order by orderno asc";
		return paginate(pageNumber, pageSize,"select *", sql);
	}

	public int delete(String sId){
		String sql = "DELETE FROM t_zxnavigation  WHERE navigation_id IN("+sId+")";
		try {
			return Db.update(sql);
		} catch (Exception e) {
			return 0;
		}
	}
}
