package com.demo.common.model;

import com.demo.common.model.base.BaseZxrole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Zxrole extends BaseZxrole<Zxrole> {
	public static final Zxrole dao = new Zxrole();
}
