package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrders<M extends BaseOrders<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}

	public java.lang.String getOrderNo() {
		return get("orderNo");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setLogistId(java.lang.Integer logistId) {
		set("logistId", logistId);
	}

	public java.lang.Integer getLogistId() {
		return get("logistId");
	}

	public void setLogistNo(java.lang.String logistNo) {
		set("logistNo", logistNo);
	}

	public java.lang.String getLogistNo() {
		return get("logistNo");
	}

	public void setLogistMoney(java.math.BigDecimal logistMoney) {
		set("logistMoney", logistMoney);
	}

	public java.math.BigDecimal getLogistMoney() {
		return get("logistMoney");
	}

	public void setGoodsId(java.lang.Integer goodsId) {
		set("goodsId", goodsId);
	}

	public java.lang.Integer getGoodsId() {
		return get("goodsId");
	}

	public void setGoodsNumber(java.lang.Integer goodsNumber) {
		set("goodsNumber", goodsNumber);
	}

	public java.lang.Integer getGoodsNumber() {
		return get("goodsNumber");
	}

	public void setPaymentType(java.lang.Integer paymentType) {
		set("paymentType", paymentType);
	}

	public java.lang.Integer getPaymentType() {
		return get("paymentType");
	}

	public void setInvoice(java.lang.Integer invoice) {
		set("invoice", invoice);
	}

	public java.lang.Integer getInvoice() {
		return get("invoice");
	}

	public void setInvoiceTitle(java.lang.String invoiceTitle) {
		set("invoiceTitle", invoiceTitle);
	}

	public java.lang.String getInvoiceTitle() {
		return get("invoiceTitle");
	}

	public void setZipcode(java.lang.String zipcode) {
		set("zipcode", zipcode);
	}

	public java.lang.String getZipcode() {
		return get("zipcode");
	}

	public void setUserRemark(java.lang.String userRemark) {
		set("userRemark", userRemark);
	}

	public java.lang.String getUserRemark() {
		return get("userRemark");
	}

	public void setAdminRemark(java.lang.String adminRemark) {
		set("adminRemark", adminRemark);
	}

	public java.lang.String getAdminRemark() {
		return get("adminRemark");
	}

	public void setOrderMoney(java.math.BigDecimal orderMoney) {
		set("orderMoney", orderMoney);
	}

	public java.math.BigDecimal getOrderMoney() {
		return get("orderMoney");
	}

	public void setAddTime(java.util.Date addTime) {
		set("addTime", addTime);
	}

	public java.util.Date getAddTime() {
		return get("addTime");
	}

	public void setDeliverTime(java.lang.String deliverTime) {
		set("deliverTime", deliverTime);
	}

	public java.lang.String getDeliverTime() {
		return get("deliverTime");
	}
	
	public void setZchannelName(java.lang.String zchannelName) {
		set("zchannel_name", zchannelName);
	}

	public java.lang.String getZchannelName() {
		return get("zchannel_name");
	}
	
	public void setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
	}

	public java.lang.String getGoodsName() {
		return get("goods_name");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}
	public void setPackageId(java.lang.Integer packageId) {
		set("package_id", packageId);
	}

	public java.lang.Integer getPackageId() {
		return get("package_id");
	}
	
	public void setPackageNumber(java.lang.Integer packageNumber) {
		set("package_number", packageNumber);
	}

	public java.lang.Integer getPackageNumber() {
		return get("package_number");
	}
	
	
}
