package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZxrole<M extends BaseZxrole<M>> extends Model<M> implements IBean {

	public void setRoleId(java.lang.Long roleId) {
		set("roleId", roleId);
	}

	public java.lang.Long getRoleId() {
		return get("roleId");
	}

	public void setRoleName(java.lang.String roleName) {
		set("roleName", roleName);
	}

	public java.lang.String getRoleName() {
		return get("roleName");
	}

	public void setActionIds(java.lang.String actionIds) {
		set("actionIds", actionIds);
	}

	public java.lang.String getActionIds() {
		return get("actionIds");
	}

}
