package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZxscreen<M extends BaseZxscreen<M>> extends Model<M> implements IBean {

	public void setScreenId(java.lang.Integer screenId) {
		set("screenId", screenId);
	}

	public java.lang.Integer getScreenId() {
		return get("screenId");
	}

	public void setImgText(java.lang.String imgText) {
		set("imgText", imgText);
	}

	public java.lang.String getImgText() {
		return get("imgText");
	}

	public void setScreenImgUrl(java.lang.String screenImgUrl) {
		set("screenImgUrl", screenImgUrl);
	}

	public java.lang.String getScreenImgUrl() {
		return get("screenImgUrl");
	}

	public void setScreenActionUrl(java.lang.String screenActionUrl) {
		set("screenActionUrl", screenActionUrl);
	}

	public java.lang.String getScreenActionUrl() {
		return get("screenActionUrl");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setAddTime(java.util.Date addTime) {
		set("addTime", addTime);
	}

	public java.util.Date getAddTime() {
		return get("addTime");
	}

}
