package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZxdegrees<M extends BaseZxdegrees<M>> extends Model<M> implements IBean {

	public void setDegreesId(java.lang.Integer degreesId) {
		set("degreesId", degreesId);
	}

	public java.lang.Integer getDegreesId() {
		return get("degreesId");
	}

	public void setDegreesName(java.lang.String degreesName) {
		set("degreesName", degreesName);
	}

	public java.lang.String getDegreesName() {
		return get("degreesName");
	}

	public void setFlavorName(java.lang.String flavorName) {
		set("flavorName", flavorName);
	}

	public java.lang.String getFlavorName() {
		return get("flavorName");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
