package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTjorder<M extends BaseTjorder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}
	
	public void setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
	}

	public java.lang.String getGoodsName() {
		return get("goods_name");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}
	
	public void setPackageNumber(java.lang.Integer packageNumber) {
		set("package_number", packageNumber);
	}

	public java.lang.Integer getPackageNumber() {
		return get("package_number");
	}
	
	public void setZchannelName(java.lang.String zchannelName) {
		set("zchannel_name", zchannelName);
	}

	public java.lang.String getZchannelName() {
		return get("zchannel_name");
	}
	
	public void setAddTime(java.util.Date addTime) {
		set("addTime", addTime);
	}

	public java.util.Date getAddTime() {
		return get("addTime");
	}
}
