package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZxbanner<M extends BaseZxbanner<M>> extends Model<M> implements IBean {

	public void setBannerId(java.lang.Long bannerId) {
		set("banner_id", bannerId);
	}

	public java.lang.Long getBannerId() {
		return get("banner_id");
	}

	public void setBannerName(java.lang.String bannerName) {
		set("banner_name", bannerName);
	}

	public java.lang.String getBannerName() {
		return get("banner_name");
	}

	public void setAddTime(java.lang.Long addTime) {
		set("add_Time", addTime);
	}

	public java.lang.Long getAddTime() {
		return get("add_Time");
	}

	public void setCreator(java.lang.Long creator) {
		set("creator", creator);
	}

	public java.lang.Long getCreator() {
		return get("creator");
	}

	public void setModTime(java.lang.Long modTime) {
		set("mod_Time", modTime);
	}

	public java.lang.Long getModTime() {
		return get("mod_Time");
	}

	public void setUpdater(java.lang.Long updater) {
		set("updater", updater);
	}

	public java.lang.Long getUpdater() {
		return get("updater");
	}

}
