package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDelivery<M extends BaseDelivery<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setZchannelId(java.lang.Integer zchannelId) {
		set("zchannel_id", zchannelId);
	}

	public java.lang.Integer getZchannelId() {
		return get("zchannel_id");
	}

	public void setFchannelId(java.lang.Integer fchannelId) {
		set("fchannel_id", fchannelId);
	}

	public java.lang.Integer getFchannelId() {
		return get("fchannel_id");
	}

	public void setZchannelName(java.lang.String zchannelName) {
		set("zchannel_name", zchannelName);
	}

	public java.lang.String getZchannelName() {
		return get("zchannel_name");
	}

	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}

	public java.lang.Integer getGoodsId() {
		return get("goods_id");
	}

	public void setGoodsChannelRate(java.lang.Integer goodsChannelRate) {
		set("goods_channel_rate", goodsChannelRate);
	}

	public java.lang.Integer getGoodsChannelRate() {
		return get("goods_channel_rate");
	}

	public void setImgUri(java.lang.String imgUri) {
		set("img_uri", imgUri);
	}

	public java.lang.String getImgUri() {
		return get("img_uri");
	}

	public void setZchannelLink(java.lang.String zchannelLink) {
		set("zchannel_link", zchannelLink);
	}

	public java.lang.String getZchannelLink() {
		return get("zchannel_link");
	}

	public void setStartTime(java.lang.String startTime) {
		set("start_time", startTime);
	}

	public java.lang.String getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.lang.String endTime) {
		set("end_time", endTime);
	}

	public java.lang.String getEndTime() {
		return get("end_time");
	}

	public void setAddTime(java.util.Date addTime) {
		set("add_time", addTime);
	}

	public java.util.Date getAddTime() {
		return get("add_time");
	}

	public void setDelivery(java.lang.Integer delivery) {
		set("delivery", delivery);
	}

	public java.lang.Integer getDelivery() {
		return get("delivery");
	}
	
	public java.lang.String getSetTime() {
		return get("setTime");
	}

	public void setSetTime(java.lang.String setTime) {
		set("setTime", setTime);
	}
	
	public void setPaidMoney(java.math.BigDecimal paidMoney) {
		set("paidMoney", paidMoney);
	}

	public java.math.BigDecimal getPaidMoney() {
		return get("paidMoney");
	}
	public void setNoMoney(java.math.BigDecimal noMoney) {
		set("noMoney", noMoney);
	}

	public java.math.BigDecimal getNoMoney() {
		return get("noMoney");
	}
	
	public void setLogistMoney(java.math.BigDecimal logistMoney) {
		set("logistMoney", logistMoney);
	}

	public java.math.BigDecimal getLogistMoney() {
		return get("logistMoney");
	}
	
	public void setOrdersNumber(java.lang.Integer ordersNumber) {
		set("ordersNumber", ordersNumber);
	}

	public java.lang.Integer getOrdersNumber() {
		return get("ordersNumber");
	}
	public void setOrdersNumbers(java.lang.Integer ordersNumbers) {
		set("ordersNumbers", ordersNumbers);
	}

	public java.lang.Integer getOrdersNumbers() {
		return get("ordersNumbers");
	}
	
	public void setOrderMoney(java.math.BigDecimal orderMoney) {
		set("orderMoney", orderMoney);
	}

	public java.math.BigDecimal getOrderMoney() {
		return get("orderMoney");
	}
	public void setOrderMoneys(java.math.BigDecimal orderMoneys) {
		set("orderMoneys", orderMoneys);
	}

	public java.math.BigDecimal getOrderMoneys() {
		return get("orderMoneys");
	}
	public void setOrderMoneyx(java.math.BigDecimal orderMoneyx) {
		set("orderMoneyx", orderMoneyx);
	}

	public java.math.BigDecimal getOrderMoneyx() {
		return get("orderMoneyx");
	}
}
