package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZxprice<M extends BaseZxprice<M>> extends Model<M> implements IBean {

	public void setPriceId(java.lang.Integer priceId) {
		set("priceId", priceId);
	}

	public java.lang.Integer getPriceId() {
		return get("priceId");
	}

	public void setPriceUrl(java.lang.String priceUrl) {
		set("priceUrl", priceUrl);
	}

	public java.lang.String getPriceUrl() {
		return get("priceUrl");
	}

	public void setPriceName(java.lang.Integer priceName) {
		set("priceName", priceName);
	}

	public java.lang.Integer getPriceName() {
		return get("priceName");
	}

}
