package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZxarticleCategory<M extends BaseZxarticleCategory<M>> extends Model<M> implements IBean {

	public void setArticleCategoryId(java.lang.Long articleCategoryId) {
		set("article_category_id", articleCategoryId);
	}

	public java.lang.Long getArticleCategoryId() {
		return get("article_category_id");
	}

	public void setArticleCategoryName(java.lang.String articleCategoryName) {
		set("article_category_name", articleCategoryName);
	}

	public java.lang.String getArticleCategoryName() {
		return get("article_category_name");
	}

	public void setOrderno(java.lang.Integer orderno) {
		set("orderno", orderno);
	}

	public java.lang.Integer getOrderno() {
		return get("orderno");
	}

	public void setAddTime(java.lang.String addTime) {
		set("add_time", addTime);
	}

	public java.lang.String getAddTime() {
		return get("add_time");
	}

	public void setCreator(java.lang.Long creator) {
		set("creator", creator);
	}

	public java.lang.Long getCreator() {
		return get("creator");
	}

	public void setModTime(java.lang.String modTime) {
		set("mod_time", modTime);
	}

	public java.lang.String getModTime() {
		return get("mod_time");
	}

	public void setUpdater(java.lang.Long updater) {
		set("updater", updater);
	}

	public java.lang.Long getUpdater() {
		return get("updater");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
