package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZxnavigation<M extends BaseZxnavigation<M>> extends Model<M> implements IBean {

	public void setNavigationId(java.lang.Long navigationId) {
		set("navigation_id", navigationId);
	}

	public java.lang.Long getNavigationId() {
		return get("navigation_id");
	}

	public void setNavigationName(java.lang.String navigationName) {
		set("navigation_name", navigationName);
	}

	public java.lang.String getNavigationName() {
		return get("navigation_name");
	}

	public void setNavigationUrl(java.lang.String navigationUrl) {
		set("navigation_url", navigationUrl);
	}

	public java.lang.String getNavigationUrl() {
		return get("navigation_url");
	}

	public void setClassName(java.lang.String className) {
		set("class_name", className);
	}

	public java.lang.String getClassName() {
		return get("class_name");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setOrderno(java.lang.Long orderno) {
		set("orderno", orderno);
	}

	public java.lang.Long getOrderno() {
		return get("orderno");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setAddTime(java.lang.Long addTime) {
		set("add_time", addTime);
	}

	public java.lang.Long getAddTime() {
		return get("add_time");
	}

	public void setCreator(java.lang.Long creator) {
		set("creator", creator);
	}

	public java.lang.Long getCreator() {
		return get("creator");
	}

	public void setModTime(java.lang.Long modTime) {
		set("mod_time", modTime);
	}

	public java.lang.Long getModTime() {
		return get("mod_time");
	}

	public void setUpdater(java.lang.Long updater) {
		set("updater", updater);
	}

	public java.lang.Long getUpdater() {
		return get("updater");
	}

}
