package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZxad<M extends BaseZxad<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setBannerId(java.lang.Integer bannerId) {
		set("banner_id", bannerId);
	}

	public java.lang.Integer getBannerId() {
		return get("banner_id");
	}

	public void setUri(java.lang.String uri) {
		set("uri", uri);
	}

	public java.lang.String getUri() {
		return get("uri");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setStartTime(java.lang.String startTime) {
		set("start_time", startTime);
	}

	public java.lang.String getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.lang.String endTime) {
		set("end_time", endTime);
	}

	public java.lang.String getEndTime() {
		return get("end_time");
	}

	public void setOrderno(java.lang.Integer orderno) {
		set("orderno", orderno);
	}

	public java.lang.Integer getOrderno() {
		return get("orderno");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setAddTime(java.lang.String addTime) {
		set("add_time", addTime);
	}

	public java.lang.String getAddTime() {
		return get("add_time");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}

	public java.lang.String getCreator() {
		return get("creator");
	}

	public void setEditTime(java.lang.String editTime) {
		set("edit_time", editTime);
	}

	public java.lang.String getEditTime() {
		return get("edit_time");
	}

	public void setUpdater(java.lang.String updater) {
		set("updater", updater);
	}

	public java.lang.String getUpdater() {
		return get("updater");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}
	
	public void setIsShow(java.lang.Integer isShow) {
		set("isShow", isShow);
	}

	public java.lang.Integer getIsShow() {
		return get("isShow");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}
	
	public void setBannerName(java.lang.String bannerName) {
		set("banner_name", bannerName);
	}

	public java.lang.String getBannerName() {
		return get("banner_name");
	}
}
