package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZchannel<M extends BaseZchannel<M>> extends Model<M> implements IBean {

	public void setZchannelId(java.lang.Long zchannelId) {
		set("zchannel_id", zchannelId);
	}

	public java.lang.Long getZchannelId() {
		return get("zchannel_id");
	}

	public void setFchannelId(java.lang.Integer fchannelId) {
		set("fchannel_id", fchannelId);
	}

	public java.lang.Integer getFchannelId() {
		return get("fchannel_id");
	}

	public void setZchannelName(java.lang.String zchannelName) {
		set("zchannel_name", zchannelName);
	}

	public java.lang.String getZchannelName() {
		return get("zchannel_name");
	}

	public void setAddTime(java.util.Date addTime) {
		set("add_time", addTime);
	}

	public java.util.Date getAddTime() {
		return get("add_time");
	}

}
