package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZxarticle<M extends BaseZxarticle<M>> extends Model<M> implements IBean {

	public void setArticleId(java.lang.Long articleId) {
		set("article_id", articleId);
	}

	public java.lang.Long getArticleId() {
		return get("article_id");
	}

	public void setArticleCategoryId(java.lang.Long articleCategoryId) {
		set("article_category_id", articleCategoryId);
	}

	public java.lang.Long getArticleCategoryId() {
		return get("article_category_id");
	}
	
	public void setArticleCategoryName(java.lang.String articleCategoryName) {
		set("article_category_name", articleCategoryName);
	}

	public java.lang.String getArticleCategoryName() {
		return get("article_category_name");
	}

	public void setFpid(java.lang.Integer fpid) {
		set("fpid", fpid);
	}

	public java.lang.Integer getFpid() {
		return get("fpid");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setImageText(java.lang.String imageText) {
		set("imageText", imageText);
	}

	public java.lang.String getImageText() {
		return get("imageText");
	}

	public void setImgUri(java.lang.String imgUri) {
		set("img_uri", imgUri);
	}

	public java.lang.String getImgUri() {
		return get("img_uri");
	}

	public void setSource(java.lang.String source) {
		set("source", source);
	}

	public java.lang.String getSource() {
		return get("source");
	}

	public void setSourceValue(java.lang.String sourceValue) {
		set("source_value", sourceValue);
	}

	public java.lang.String getSourceValue() {
		return get("source_value");
	}

	public void setPublishTime(java.lang.String publishTime) {
		set("publish_time", publishTime);
	}

	public java.lang.String getPublishTime() {
		return get("publish_time");
	}

	public void setMetaKeywords(java.lang.String metaKeywords) {
		set("meta_keywords", metaKeywords);
	}

	public java.lang.String getMetaKeywords() {
		return get("meta_keywords");
	}

	public void setIsShow(java.lang.Integer isShow) {
		set("is_show", isShow);
	}

	public java.lang.Integer getIsShow() {
		return get("is_show");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setContentSummary(java.lang.String contentSummary) {
		set("content_summary", contentSummary);
	}

	public java.lang.String getContentSummary() {
		return get("content_summary");
	}

	public void setAddTime(java.lang.String addTime) {
		set("add_time", addTime);
	}

	public java.sql.Timestamp getAddTime() {
		return get("add_time");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		String content = get("content");
		//content = content.replaceAll("\\.\\./", "");
		return content;
	}

	public void setModTime(java.lang.String modTime) {
		set("mod_time", modTime);
	}

	public java.lang.String getModTime() {
		return get("mod_time");
	}

	public void setUpdater(java.lang.Integer updater) {
		set("updater", updater);
	}

	public java.lang.Integer getUpdater() {
		return get("updater");
	}

	public void setSeoKey(java.lang.String seoKey) {
		set("seo_key", seoKey);
	}

	public java.lang.String getSeoKey() {
		return get("seo_key");
	}

	public void setSeoDesc(java.lang.String seoDesc) {
		set("seo_desc", seoDesc);
	}

	public java.lang.String getSeoDesc() {
		return get("seo_desc");
	}

	public void setSeoTitle(java.lang.String seoTitle) {
		set("seo_title", seoTitle);
	}

	public java.lang.String getSeoTitle() {
		return get("seo_title");
	}

	public void setTypeName(java.lang.String typeName) {
		set("typeName", typeName);
	}

	public java.lang.String getTypeName() {
		return get("typeName");
	}

	public void setNoticeStartTime(java.lang.String noticeStartTime) {
		set("noticeStartTime", noticeStartTime);
	}

	public java.lang.String getNoticeStartTime() {
		return get("noticeStartTime");
	}

	public void setNoticeEndTime(java.lang.String noticeEndTime) {
		set("noticeEndTime", noticeEndTime);
	}

	public java.lang.String getNoticeEndTime() {
		return get("noticeEndTime");
	}

	public void setRespon(java.lang.String respon) {
		set("respon", respon);
	}

	public java.lang.String getRespon() {
		return get("respon");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public void setAccess(java.lang.Integer access) {
		set("access", access);
	}

	public java.lang.Integer getAccess() {
		return get("access");
	}
	
	public void setOpinion(java.lang.String opinion) {
		set("opinion", opinion);
	}

	public java.lang.String getOpinion() {
		return get("opinion");
	}
}
