package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public void setGoodsId(java.lang.Long goodsId) {
		set("goods_id", goodsId);
	}

	public java.lang.Long getGoodsId() {
		return get("goods_id");
	}

	public void setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
	}

	public java.lang.String getGoodsName() {
		return get("goods_name");
	}

	public void setChannelId(java.lang.Integer channelId) {
		set("channel_id", channelId);
	}

	public java.lang.Integer getChannelId() {
		return get("channel_id");
	}

	public void setGoodsChannelRate(java.lang.Double goodsChannelRate) {
		set("goods_channel_rate", goodsChannelRate);
	}

	public java.lang.Double getGoodsChannelRate() {
		return get("goods_channel_rate");
	}

	public void setImgUri(java.lang.String imgUri) {
		set("img_uri", imgUri);
	}

	public java.lang.String getImgUri() {
		return get("img_uri");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setOrprice(java.math.BigDecimal orprice) {
		set("orprice", orprice);
	}

	public java.math.BigDecimal getOrprice() {
		return get("orprice");
	}

	public void setDiscount(java.math.BigDecimal discount) {
		set("discount", discount);
	}

	public java.math.BigDecimal getDiscount() {
		return get("discount");
	}

	public void setSave(java.math.BigDecimal save) {
		set("save", save);
	}

	public java.math.BigDecimal getSave() {
		return get("save");
	}

	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}

	public java.lang.Integer getNumber() {
		return get("number");
	}

	public void setNumberActual(java.lang.Integer numberActual) {
		set("number_actual", numberActual);
	}

	public java.lang.Integer getNumberActual() {
		return get("number_actual");
	}

	public void setResidualTime(java.lang.String residualTime) {
		set("residual_time", residualTime);
	}

	public java.lang.String getResidualTime() {
		return get("residual_time");
	}

	public void setDescribe(java.lang.String describe) {
		set("describe", describe);
	}

	public java.lang.String getDescribe() {
		return get("describe");
	}

	public void setPurchaseUri(java.lang.String purchaseUri) {
		set("purchase_uri", purchaseUri);
	}

	public java.lang.String getPurchaseUri() {
		return get("purchase_uri");
	}

	public void setIntroduceUri(java.lang.String introduceUri) {
		set("introduce_uri", introduceUri);
	}

	public java.lang.String getIntroduceUri() {
		return get("introduce_uri");
	}

	public void setCustomer(java.lang.String customer) {
		set("customer", customer);
	}

	public java.lang.String getCustomer() {
		return get("customer");
	}

	public void setPackageIds(java.lang.String packageIds) {
		set("package_ids", packageIds);
	}

	public java.lang.String getPackageIds() {
		return get("package_ids");
	}

	public void setPayment(java.lang.Integer payment) {
		set("payment", payment);
	}

	public java.lang.Integer getPayment() {
		return get("payment");
	}

	public void setRealTimeOrderno(java.lang.Integer realTimeOrderno) {
		set("real_time_orderno", realTimeOrderno);
	}

	public java.lang.Integer getRealTimeOrderno() {
		return get("real_time_orderno");
	}

	public void setRealTimePosition(java.lang.Integer realTimePosition) {
		set("real_time_position", realTimePosition);
	}

	public java.lang.Integer getRealTimePosition() {
		return get("real_time_position");
	}

	public void setRealTimeSs(java.lang.Integer realTimeSs) {
		set("real_time_ss", realTimeSs);
	}

	public java.lang.Integer getRealTimeSs() {
		return get("real_time_ss");
	}

	public void setRealTimeContent(java.lang.String realTimeContent) {
		set("real_time_content", realTimeContent);
	}

	public java.lang.String getRealTimeContent() {
		return get("real_time_content");
	}

	public void setComment(java.lang.Integer comment) {
		set("comment", comment);
	}

	public java.lang.Integer getComment() {
		return get("comment");
	}

	public void setCommentSs(java.lang.Integer commentSs) {
		set("comment_ss", commentSs);
	}

	public java.lang.Integer getCommentSs() {
		return get("comment_ss");
	}

	public void setCommentContent(java.lang.String commentContent) {
		set("comment_content", commentContent);
	}

	public java.lang.String getCommentContent() {
		return get("comment_content");
	}

	public void setBaidu(java.lang.String baidu) {
		set("baidu", baidu);
	}

	public java.lang.String getBaidu() {
		return get("baidu");
	}

	public void setYoumeng(java.lang.String youmeng) {
		set("youmeng", youmeng);
	}

	public java.lang.String getYoumeng() {
		return get("youmeng");
	}

	public void setAddTime(java.util.Date addTime) {
		set("add_time", addTime);
	}

	public java.util.Date getAddTime() {
		return get("add_time");
	}

}
