package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZxadmin<M extends BaseZxadmin<M>> extends Model<M> implements IBean {

	public void setAdminId(java.lang.Long adminId) {
		set("adminId", adminId);
	}

	public java.lang.Long getAdminId() {
		return get("adminId");
	}

	public void setRoleId(java.lang.Long roleId) {
		set("roleId", roleId);
	}

	public java.lang.Long getRoleId() {
		return get("roleId");
	}

	public void setAdminType(java.lang.String adminType) {
		set("adminType", adminType);
	}

	public java.lang.String getAdminType() {
		return get("adminType");
	}

	public void setAdmin(java.lang.String admin) {
		set("admin", admin);
	}

	public java.lang.String getAdmin() {
		return get("admin");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setAdminName(java.lang.String adminName) {
		set("adminName", adminName);
	}

	public java.lang.String getAdminName() {
		return get("adminName");
	}

	public void setIsDel(java.lang.String isDel) {
		set("isDel", isDel);
	}

	public java.lang.String getIsDel() {
		return get("isDel");
	}

	public void setAddTime(java.util.Date addTime) {
		set("addTime", addTime);
	}

	public java.util.Date getAddTime() {
		return get("addTime");
	}

	public void setCreator(java.lang.Long creator) {
		set("creator", creator);
	}

	public java.lang.Long getCreator() {
		return get("creator");
	}

	public void setModTime(java.util.Date modTime) {
		set("modTime", modTime);
	}

	public java.util.Date getModTime() {
		return get("modTime");
	}

	public void setUpdater(java.lang.Long updater) {
		set("updater", updater);
	}

	public java.lang.Long getUpdater() {
		return get("updater");
	}

}
